### ISSUE TITLE
Maybe consider to add

### ISSUE THREAD

**Issue by clamoune** [scautomation/Azure-Inventory-Workbook#10]
Hello,

I've added provisioning state in the vm compute :

Resources 
| where type == "microsoft.compute/virtualmachines"
| extend vmID = tolower(id)
| extend osDiskId= tolower(tostring(properties.storageProfile.osDisk.managedDisk.id))
**| extend provisioningState = tostring(properties.extended.instanceView.powerState.code)**
        | join kind=leftouter(resources
            | where type =~ 'microsoft.compute/disks'
            | where properties !has 'Unattached'
            | where properties has 'osType'
            | project timeCreated = tostring(properties.timeCreated), OS = tostring(properties.osType), osSku = tostring(sku.name), osDiskSizeGB = toint(properties.diskSizeGB), osDiskId=tolower(tostring(id))) on osDiskId
        | join kind=leftouter(resources
			| where type =~ 'microsoft.compute/availabilitysets'
			| extend VirtualMachines = array_length(properties.virtualMachines)
			| mv-expand VirtualMachine=properties.virtualMachines
			| extend FaultDomainCount = properties.platformFaultDomainCount
			| extend UpdateDomainCount = properties.platformUpdateDomainCount
			| extend vmID = tolower(VirtualMachine.id)
			| project AvailabilitySetID = id, vmID, FaultDomainCount, UpdateDomainCount ) on vmID
		| join kind=leftouter(resources
			| where type =~ 'microsoft.sqlvirtualmachine/sqlvirtualmachines'
			| extend SQLLicense = properties.sqlServerLicenseType
			| extend SQLImage = properties.sqlImageOffer
			| extend SQLSku = properties.sqlImageSku
			| extend SQLManagement = properties.sqlManagement
			| extend vmID = tostring(tolower(properties.virtualMachineResourceId))
			| project SQLId=id, SQLLicense, SQLImage, SQLSku, SQLManagement, vmID ) on vmID
| project-away vmID1, vmID2, osDiskId1
| extend Details = pack_all()
| project vmID, SQLId, AvailabilitySetID, **provisioningState**, OS, resourceGroup, location, subscriptionId, SQLLicense, SQLImage,SQLSku, SQLManagement, FaultDomainCount, UpdateDomainCount, Details

**Comment by scautomation** [comment]
added in latest pull request
