### ISSUE TITLE
This item is currently hidden so it is not automatically updating. in Azure invontory

### ISSUE THREAD

**Issue by manojarina** [scautomation/Azure-Inventory-Workbook#14]
Hi I am getting for all the resources **_**"This item is currently hidden so it is not automatically updating**"_**. when I am importing jason code. Please help me with this.

**Comment by mpalagir** [comment]
Hi team,

Do you have any update on that, even I too had the same Issue.

Thanks

**Comment by scautomation** [comment]
this is normal behavior. You need to click "done editing" to see the workbook in its proper mode. When in "editing" mode, all graphs and widgets are visible for editing purposes, when not editing mode the graphs and widgets are controlled by parameters to control what is visible to the user.

**Comment by mpalagir** [comment]
Hi @scautomation,

Thanks for the great innovation. It is much helpful to refer everything at one place. 

Could you please advise me why data is not reflecting for Tagged resources.

![image](https://user-images.githubusercontent.com/105036831/192787603-a5b2f0ee-d6b0-4890-877f-169e51f7c9ce.png)

I just have tweaked the query like this to reflect the tagged resources. Please correct me if i am wrong 

Resources 
| extend type = case(
type contains 'microsoft.netapp/netappaccounts', 'NetApp Accounts',
type contains "microsoft.compute", "Azure Compute",
type contains "microsoft.logic", "LogicApps",
type contains 'microsoft.keyvault/vaults', "Key Vaults",
type contains 'microsoft.storage/storageaccounts', "Storage Accounts",
type contains 'microsoft.compute/availabilitysets', 'Availability Sets',
type contains 'microsoft.operationalinsights/workspaces', 'Azure Monitor Resources',
type contains 'microsoft.operationsmanagement', 'Operations Management Resources',
type contains 'microsoft.insights', 'Azure Monitor Resources',
type contains 'microsoft.desktopvirtualization/applicationgroups', 'WVD Application Groups',
type contains 'microsoft.desktopvirtualization/workspaces', 'WVD Workspaces',
type contains 'microsoft.desktopvirtualization/hostpools', 'WVD Hostpools',
type contains 'microsoft.recoveryservices/vaults', 'Backup Vaults',
type contains 'microsoft.web', 'App Services',
type contains 'microsoft.managedidentity/userassignedidentities','Managed Identities',
type contains 'microsoft.storagesync/storagesyncservices', 'Azure File Sync',
type contains 'microsoft.hybridcompute/machines', 'ARC Machines',
type contains 'Microsoft.EventHub', 'Event Hub',
type contains 'Microsoft.EventGrid', 'Event Grid',
type contains 'Microsoft.Sql', 'SQL Resources',
type contains 'Microsoft.HDInsight/clusters', 'HDInsight Clusters',
type contains 'microsoft.devtestlab', 'DevTest Labs Resources',
type contains 'microsoft.containerinstance', 'Container Instances Resources',
type contains 'microsoft.portal/dashboards', 'Azure Dashboards',
type contains 'microsoft.containerregistry/registries', 'Container Registry',
type contains 'microsoft.automation', 'Automation Resources',
type contains 'sendgrid.email/accounts', 'SendGrid Accounts',
type contains 'microsoft.datafactory/factories', 'Data Factory',
type contains 'microsoft.databricks/workspaces', 'Databricks Workspaces',
type contains 'microsoft.machinelearningservices/workspaces', 'Machine Learnings Workspaces',
type contains 'microsoft.alertsmanagement/smartdetectoralertrules', 'Azure Monitor Resources',
type contains 'microsoft.apimanagement/service', 'API Management Services',
type contains 'microsoft.dbforpostgresql', 'PostgreSQL Resources',
type contains 'microsoft.scheduler/jobcollections', 'Scheduler Job Collections',
type contains 'microsoft.visualstudio/account', 'Azure DevOps Organization',
type contains 'microsoft.network/', 'Network Resources',
type contains 'microsoft.migrate/' or type contains 'microsoft.offazure', 'Azure Migrate Resources',
type contains 'microsoft.servicebus/namespaces', 'Service Bus Namespaces',
type contains 'microsoft.classic', 'ASM Obsolete Resources',
type contains 'microsoft.resources/templatespecs', 'Template Spec Resources',
type contains 'microsoft.virtualmachineimages', 'VM Image Templates',
type contains 'microsoft.documentdb', 'CosmosDB DB Resources',
type contains 'microsoft.alertsmanagement/actionrules', 'Azure Monitor Resources',
type contains 'microsoft.kubernetes/connectedclusters', 'ARC Kubernetes Clusters',
type contains 'microsoft.purview', 'Purview Resources',
type contains 'microsoft.security', 'Security Resources',
type contains 'microsoft.cdn', 'CDN Resources',
type contains 'microsoft.devices','IoT Resources',
type contains 'microsoft.datamigration', 'Data Migraiton Services',
type contains 'microsoft.cognitiveservices', 'Congitive Services',
type contains 'microsoft.customproviders', 'Custom Providers',
type contains 'microsoft.appconfiguration', 'App Services',
type contains 'microsoft.search', 'Search Services',
type contains 'microsoft.maps', 'Maps',
type contains 'microsoft.containerservice/managedclusters', 'AKS',
type contains 'microsoft.signalrservice', 'SignalR',
type contains 'microsoft.resourcegraph/queries', 'Resource Graph Queries',
type contains 'microsoft.batch', 'MS Batch',
type contains 'microsoft.analysisservices', 'Analysis Services',
type contains 'microsoft.synapse/workspaces', 'Synapse Workspaces',
type contains 'microsoft.synapse/workspaces/sqlpools', 'Synapse SQL Pools',
type contains 'microsoft.kusto/clusters', 'ADX Clusters',
type contains 'microsoft.resources/deploymentscripts', 'Deployment Scripts',
type contains 'microsoft.aad/domainservices', 'AD Domain Services',
type contains 'microsoft.labservices/labaccounts', 'Lab Accounts',
type contains 'microsoft.automanage/accounts', 'Automanage Accounts',
type contains 'microsoft.relay/namespaces', 'Azure Relay',
type contains 'microsoft.notificationhubs/namespaces', 'Notification Hubs',
type contains 'microsoft.digitaltwins/digitaltwinsinstances', 'Digital Twins',
strcat("Not Translated: ", type))
| where isnotempty(tags)
| extend env=tags.Environment
| project name, type,tags,kind,resourceGroup,subscriptionId,env

**Comment by mpalagir** [comment]
I think i also had chosen the environment but still data is not reflecting

**Comment by scautomation** [comment]
the message in the widget says that application isn't set, did you remove the application parameter from the query?

**Comment by mpalagir** [comment]
Hi @scautomation (Bill),

Thanks for responding to my query.

Yes, as you suggested i have removed the Application from query and pasted the json but still it is not giving the expected results. Please have a look into this.

![image](https://user-images.githubusercontent.com/105036831/192793008-c192ec68-a3fd-4628-ae85-e72d1de127c0.png)

Could you please share the updated Json that works for tagged resources as well.

Thank you.

**Comment by scautomation** [comment]
so what was in the workbook, worked for the environments I was in ;-)  
how it works in your environment is going to vary based on how tags are applied to resources. 

I have several examples of using parameters on my blog
https://www.cloudsma.com/2021/10/build-azure-policy-compliance-workbook/

pretty much all of my workbooks have parameters, here is a list of most of them
https://www.cloudsma.com/2020/11/import-azure-monitor-workbooks/

additionally, i have a repo of ARG Examples https://github.com/scautomation/AzureResourceGraph-Examples

in particular i have a section just for querying things by tags https://github.com/scautomation/AzureResourceGraph-Examples/tree/master/tagQueries

hope this helps!

**Comment by mpalagir** [comment]
Hi @scautomation,

Thank you very much for sharing this.

In my environment we had environment type as Prod. So i had selected that but the results were not as expected. I will try the queries as you suggested but in the meanwhile  could you please help me with the Json without having Tagged resources section that is appearing in the workbook since we are only concerned about untagged section not the tagged resources for now. I tried to remove the Tagged section from Json but it doesn't work Billy.

Thanks for your kind support.
Kind regards,
mpalagir

**Comment by mpalagir** [comment]
Also to update you seems publicIpAddress are not populating for VMs. When i give the join kind as fullouter I could see the public IP details for few machines but most of them were showing as empty and in the workbook visualization it is showing as none

Could you please check that as well, if possible .

**Comment by scautomation** [comment]
just checked in our lab sub, and i am able to see both the publicIP resource ID as well as the Public IP address under the VM Netorking tab under Compute.

**Comment by mpalagir** [comment]
Hi @scautomation,

Thanks for the response.

I have observed that You have joined networkinterfaces table and Ipaddresstable on the common column publicIpId where publicIpId have no results from networkinterfaces table.

Resources
| where type =~ 'microsoft.network/networkinterfaces'
| extend ipConfigsCount=array_length(properties.ipConfigurations)
| mv-expand ipconfig=properties.ipConfigurations
| where ipConfigsCount == 1 or ipconfig.properties.primary =~ 'true'
| project nicId = id, privateIP= tostring(ipconfig.properties.privateIPAddress), **publicIpId = tostring(ipconfig.properties.publicIPAddress.id), subscriptionId**

Here from the ipconfig properties there is no meta for publicIpAddress that's where it's unable to match the respective publicIpAddresses can you please look into it.

**Comment by mpalagir** [comment]
Thank you @scautomation. Seems in my environment we have only couple of the publicIds present part of Nic and that is the matching column here for tables( Networkinterfaces and publicIpaddress resources)
