### ISSUE TITLE
Need suggestion how to filter all visualization based on resource groups

### ISSUE THREAD

**Issue by azureiac** [scautomation/Azure-Inventory-Workbook#16]
Hi Team,

The workbook is based on subscription filter. 

Is there any quicker way to add drop down for resource groups and filter all visualization based of resources groups?

Please guide

**Comment by scautomation** [comment]
you would have to add a new parameter with the resource groups and then add that parameter to ALL the queries you want to filter on resource group.

you can use other parameters in the workbook, or my other workbooks to see how to preform this task.
