### ISSUE TITLE
Storage and Backup used space

### ISSUE THREAD

**Issue by egebaek** [scautomation/Azure-Inventory-Workbook#17]
Can you make so thaat the used space for backup is shown and what backup items there is in it?
<img width="556" alt="image" src="https://user-images.githubusercontent.com/33511713/207884970-003b0db5-31da-4e40-8d88-82451d772691.png">

**Comment by scautomation** [comment]
do you know if this info is in Azure Resource Graph? The issue sometimes with requests like this is that I would love to do it, but often the limitation is what ARG pulls into its system.

**Comment by scautomation** [comment]
looked myself, it is not available. however you could make ARM api calls to get this information, but it would be limited to one storage account at a time.
