### ISSUE TITLE
Orphaned disk show ActiveSAS disk also

### ISSUE THREAD

**Issue by aavdberg** [scautomation/Azure-Inventory-Workbook#8]

**Comment by aavdberg** [comment]
It's from ASR Replica

**Comment by aavdberg** [comment]
Resources  
| where type contains "microsoft.compute/disks" 
| extend diskState = tostring(properties.diskState)
| where managedBy == "" and diskState != 'ActiveSAS'
    or diskState == 'Unattached' and diskState != 'ActiveSAS'
| project id, diskState, resourceGroup, location, subscriptionId

**Comment by scautomation** [comment]
added in latest pull request
