### ISSUE TITLE
Issue gathering tagged resources

### ISSUE THREAD

**Issue by repogh** [scautomation/Azure-Inventory-Workbook#9]
<img width="580" alt="Capture1" src="https://user-images.githubusercontent.com/49834835/129541142-69033f4c-b3af-464a-908f-7b9750c2d438.PNG">

When clicking on "Tagged Resources" I get the below message.

I have deployed the most recent ARM template

**Comment by clamoune** [comment]
Your tag's must be Environment and Application if you don't want to make any change on it

**Comment by scautomation** [comment]
@repogh  as @clamoune  says you need to modify the tags to fit your environment.
